name: Update VPN Subscription

on:
  schedule:
    - cron: '0 */6 * * *' # Запуск каждые 6 часов
  workflow_dispatch:      # Кнопка ручного запуска

permissions:
  contents: write         # Явное разрешение на запись изменений

jobs:
  update-sub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests qrcode pillow

      - name: Run scanner
        run: python scanner.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add sub.txt subscription_qr.png
          git commit -m "Auto-update: Found working nodes" || exit 0
          git push origin main
